import {
    FiFolder,
    FiHome,
    FiBook,
    FiSettings,
    FiStar,
    FiHeart,
    FiMusic,
    FiCamera,
    FiImage,
    FiVideo,
    FiFileText,
    FiCode,
    FiTool,
    FiUser,
    FiUsers,
    FiShoppingCart,
    FiDollarSign,
    FiCalendar,
    FiClock,
    FiMail,
    FiPhone,
  } from "react-icons/fi";
  import {
    FolderOpen,
    Archive,
    Bookmark,
    Briefcase,
    Coffee,
    Gift,
    Globe,
    GraduationCap,
    Lightbulb,
    MapPin,
    Palette,
    Shield,
    Target,
    Zap,
  } from "lucide-react";

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  export const iconMap: Record<string, React.ComponentType<any>> = {
    folder: FiFolder,
    home: FiHome,
    book: FiBook,
    settings: FiSettings,
    star: FiStar,
    heart: FiHeart,
    music: FiMusic,
    camera: FiCamera,
    image: FiImage,
    video: FiVideo,
    file: FiFileText,
    code: FiCode,
    tools: FiTool,
    user: FiUser,
    users: FiUsers,
    cart: FiShoppingCart,
    dollar: FiDollarSign,
    calendar: FiCalendar,
    clock: FiClock,
    mail: FiMail,
    phone: FiPhone,
    folderOpen: FolderOpen,
    archive: Archive,
    bookmark: Bookmark,
    briefcase: Briefcase,
    coffee: Coffee,
    gift: Gift,
    globe: Globe,
    cap: GraduationCap,
    bulb: Lightbulb,
    pin: MapPin,
    palette: Palette,
    shield: Shield,
    target: Target,
    zap: Zap,
  };
  